### ISSUE TITLE
I have some questions for training

### ISSUE THREAD

**Issue by Ohraincu** [Maclory/SPSR#12]
您好，我按照您的过程创建了训练数据集之后，跑了大概五千步发现val测试的结果总是黑色的，但是训练过程中loss输出都很小，想问下您在训练的时候是大概在多少步的时候出现的视觉效果为彩色的图呢。

**Comment by Ohraincu** [comment]
我是重新训练的没有使用任何预训练模型，这样会影响收敛的速度嘛？

**Comment by Maclory** [comment]
您好，如果训练中没有加载预训练模型的话可能需要调整一下训练的设置，比如调整Branch_pretrain和Branch_init_iters，另外训练初期只用pixelloss并适当增加学习率可以提高收敛速度。

**Comment by Ohraincu** [comment]
谢谢你。另外想了解一下您生成的div2k_sub大概是多少张图呢，我这边显示的train_images是32,208张。

**Comment by Maclory** [comment]
是的，和我们的一样

**Comment by Ohraincu** [comment]
非常感谢解答！

**Comment by Ohraincu** [comment]
你好，我在训练初期使用了rrdb的预训练模型，其他参数除了batchsize小了一点其他都没有改，想问你使用set14的val过程psnr大概是在什么时候到达的26呢，我现在一直在25左右上不去。

**Comment by Maclory** [comment]
> 你好，我在训练初期使用了rrdb的预训练模型，其他参数除了batchsize小了一点其他都没有改，想问你使用set14的val过程psnr大概是在什么时候到达的26呢，我现在一直在25左右上不去。

你好，我们在训练中val过程的psnr也不会到26，val中的数值只是参考，计算psnr的过程和测试时是不同的。

**Comment by scutlrr** [comment]
> > 你好，我在训练初期使用了rrdb的预训练模型，其他参数除了batchsize小了一点其他都没有改，想问你使用set14的val过程psnr大概是在什么时候到达的26呢，我现在一直在25左右上不去。
> 
> 你好，我们在训练中val过程的psnr也不会到26，val中的数值只是参考，计算psnr的过程和测试时是不同的。

请问为什么验证和测试时psnr会是不同的呢？计算的方法不是一致的吗？

**Comment by Maclory** [comment]
目前代码的验证和测试过程中计算方法是有差别的，不过你可以改成一致的~

**Comment by xcc19970423** [comment]
你好，为什么在训练的时候PSNR为Nan,没有值
