### ISSUE TITLE
关于总的训练次数

### ISSUE THREAD

**Issue by Yueziyu** [Maclory/SPSR#14]
您好，我在查看训练设置文件的时候发现总的迭代次数是500W次，这样训练一共需要大概4660多个epoch，请问总的迭代次数设定500W次是正确的吗？

**Comment by Maclory** [comment]
你好，500W只是随意设置的一个值，实际训练不需要这么多代，有较好的模型就可以停下。不过我还是把这里的设置修改一下吧，谢谢你的提醒。

**Comment by Yueziyu** [comment]
谢谢你
