### ISSUE TITLE
The SSIM indexes seem irregular on set14 and urban100.

### ISSUE THREAD

**Issue by HuiZeng** [Maclory/SPSR#15]
Hi, the SSIM indexes seem too high on the set14 and urban100 datasets. 
![image](https://user-images.githubusercontent.com/12780780/85198611-947e9000-b31c-11ea-9de9-5db5704de6c9.png)
Especially on the urban100, SSIM=0.95 seems too high given the PSNR is only ~25dB.

It seems that ESRGAN obtains SSIM_Y at about 0.71 and 0.73 on the Set14 and urban100 datasets, respectively. 

Please double check those numbers.

**Comment by Maclory** [comment]
Hi, our code to calculate SSIM values is different from that of ESRGAN. In fact, both two versions of code are from [SSIM link](https://ece.uwaterloo.ca/~z70wang/research/ssim/). However, ESRGAN obtains the values by `ssim_index.m` while we use `ssim.m`, which includes a downsampling process as suggested by [SSIM link](https://ece.uwaterloo.ca/~z70wang/research/ssim/). Although our absolute values are different from ESRGAN, the relative values are not affected.

**Comment by HuiZeng** [comment]
Thanks for your explanation.
