### ISSUE TITLE
想请问下训练的迭代次数和时间

### ISSUE THREAD

**Issue by Yueziyu** [Maclory/SPSR#16]
您好，我想请问下你们在训练spsr的时候大概是在多少次迭代收敛的，我训练到41万次的时候画出的指标曲线还在振荡，大概训练了多久？

**Comment by Maclory** [comment]
你好，GAN模型的训练一般很难达到收敛，我们也是大概训了40万代，用了几天的时间。

**Comment by Yueziyu** [comment]
谢谢，另外我想再请问下，在训练的时候有没有尝试过其他的学习率，可以使网络收敛的平滑一些？

**Comment by Maclory** [comment]
我们为了保证对比的公平性，是直接采用了ESRGAN的学习率来训练的。不过我认为可以尝试其他的学习率，有可能会有更理想的效果。

**Comment by Yueziyu** [comment]
非常感谢
