### ISSUE TITLE
Preprocess Datasets' Problem

### ISSUE THREAD

**Issue by Lufei-github** [Maclory/SPSR#17]
I use DIV2K dataset as the training set.In the step of Generate Sub-Images,I can generate 32208 sub_images of HR images,but only genearate 12 sub_images of LR images.Later,I found out that HR images are about 2040*1404 pixels or 2040* 1848 pixels,however the LR images are about 510*351 pixels,510* 462 pixels.So one HR image can generate about 40 HR sub_images,and one LR image can only generate 1 LR sub_image,even zero LR sub_image.So what should do to have the same number of HR sub_images and LR sub_images?Looking forward to your reply!

**Comment by Yueziyu** [comment]
I sampled the SEGMented HR image up and down to get the LR image.

**Comment by AcEvolution** [comment]
The default parameters are designed for HR, so you need to change the parameters in `extract_subimgs_single.py` to fit the scale of LR images.

These parameters are `crop_sz`, `step` and `thres_sz`.

You need to assure that these parameters for HR is 4 times lager than the parameters for LR.

For example:

If you use `crop_sz=480`, `step=240` and `thres_sz=48` for HR, you need to change them to `crop_sz=120`, `step=60` and `thres_sz=12` when you process LR images.

And you will find that the number of HR sub-images is the same as the number of LR sub-images.
