### ISSUE TITLE
Unknown error occuring 

### ISSUE THREAD

**Issue by nanmehta** [Maclory/SPSR#20]
`RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable`

hey thanks for your code, I need yor help as I am new to pytorch and not getting what this error is saying , while implementing the test code

**Comment by Maclory** [comment]
Hi, you can refer to [this link](https://github.com/dask/distributed/issues/2520) to fix the issue.
