### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by InstantWindy** [Maclory/SPSR#21]
Hi. When I set the batch size to 16, the training only takes up about 6G of GPU memory, but when I run to the verification set, the memory overflow error will be reported. My GPU memory is 11G. What is the batch size you set during training and how much memory is used? Moreover, it is very slow to train. It takes a long time to iterate 5000 times. Is there any way to save GPU memory? Thanks.

**Comment by Maclory** [comment]
Hi, the memory overflow error is caused by training, instead of validation. In fact, we only update a part of the parameters for the first 5000 iterations and update all the parameters after the 5000th iteration. So setting a smaller batch size may solve the problem.
