### ISSUE TITLE
There is no difference between LR and SR

### ISSUE THREAD

**Issue by Pinnh** [Maclory/SPSR#22]
There is no difference between LR and SR , when I test the model you provide which in  BaiduCloud
Is there anything wrong?

Input:
![a](https://user-images.githubusercontent.com/11919692/91011876-b693d780-e617-11ea-8773-2e9c5e94ee24.jpg)

Output:
![a](https://user-images.githubusercontent.com/11919692/91011906-c4495d00-e617-11ea-8d2d-c33949344b93.png)

Log detail:

export CUDA_VISIBLE_DEVICES=0
20-08-24 14:23:53.230 - INFO:   name: SPSR
  model: spsr
  scale: 4
  gpu_ids: [0]
  datasets:[
    test_1:[
      name: set5
      mode: LR
      dataroot_LR: ../images/
      phase: test
      scale: 4
      data_type: img
    ]
  ]
  path:[
    root: ./
    pretrain_model_G: ../SPSR/spsr.pth
    results_root: ./results/SPSR
    log: ./results/SPSR
  ]
  network_G:[
    which_model_G: spsr_net
    norm_type: None
    mode: CNA
    nf: 64
    nb: 23
    in_nc: 3
    out_nc: 3
    gc: 32
    group: 1
    scale: 4
  ]
  is_train: False

20-08-24 14:23:53.231 - INFO: Dataset [LRDataset - set5] is created.
20-08-24 14:23:53.231 - INFO: Number of test images in [set5]: 1
20-08-24 14:24:01.398 - INFO: Loading pretrained model for G [../SPSR/spsr.pth] ...
20-08-24 14:24:02.428 - INFO: Model [SPSRModel] is created.
20-08-24 14:24:02.429 - INFO: 
Testing [set5]...
20-08-24 14:24:03.315 - INFO: a

**Comment by Maclory** [comment]
Hi, thank you for your interest in our work. It can be observed that there are checkerboard artifacts in the output image. So I think this may be caused by the JPEG format since such artifacts are typical of the JPEG images.
