### ISSUE TITLE
resume training问题

### ISSUE THREAD

**Issue by DoubleKing0625** [Maclory/SPSR#23]
Hi,  我看到resume training时候, 
只load model_G,  最多会load model_D,  而model_D_grad不会load进来
这个是合理的吗?

**Comment by Maclory** [comment]
你好，resume training部分的代码确实是有问题的，需要增加model_D_grad模型的加载。我们在训练的时候基本都是一次性训练，基本没有用到resume的部分，所以之前没有注意到这部分代码的问题，抱歉。
