### ISSUE TITLE
模型的训练是如何安排的？

### ISSUE THREAD

**Issue by Feihongzhu** [Maclory/SPSR#26]
你好呀~我有几个问题想请教你：
1. 想重新训练你的模型看看不采用对抗训练的方式（只训练生成器），效果是如何的？你们有尝试过只训练生成器部分吗？
2. 现在文章的训练方式是不是预训练5000轮，再对抗训练5e6轮？
3. 在第二问的基础上，文章提到用了一个PSNR导向的模型作为预训练模型，请问在预训练中，是不是只有L1或L2作为模型的loss？
4. 如果只要训练生成器，应该怎么设置预训练和正式训练的轮次？

**Comment by Maclory** [comment]
嗨，只训练生成器的话可以试一下，训练轮次应该不需要改动。5e6只是设置的一个最大值，实际训练不需要这么多轮。预训练模型我们是直接使用[ESRGAN](https://github.com/xinntao/ESRGAN)中提供的模型，具体训练细节可以参考相应的文章。

**Comment by Feihongzhu** [comment]
> 嗨，只训练生成器的话可以试一下，训练轮次应该不需要改动。5e6只是设置的一个最大值，实际训练不需要这么多轮。预训练模型我们是直接使用[ESRGAN](https://github.com/xinntao/ESRGAN)中提供的模型，具体训练细节可以参考相应的文章。

嗨，请问你用的预训练模型是同时初始化SR branch 和 grad branch吗？

**Comment by Maclory** [comment]
不是的，只初始化SR branch
