### ISSUE TITLE
About evaluation toolbox configuration.

### ISSUE THREAD

**Issue by lovepiano** [Maclory/SPSR#29]
Hi,
I follow your tips,but I can not still import matlab.engine. I want to know how to configure it by yourself, including all kinds of enviroment settings. I have tried many ways, but no one can succeed.  It can not be installed in Python 3.x, only in Python 2.7. Thanks! 
![微信截图_20201217153019](https://user-images.githubusercontent.com/37391982/102456903-dc3c6500-407c-11eb-862a-616c6d079657.png)

**Comment by Maclory** [comment]
Hi, sorry for the late reply. I think you can first check whether Matlab works properly in your environment.
