### ISSUE TITLE
关于root中的path

### ISSUE THREAD

**Issue by floodgone** [Maclory/SPSR#30]
您好，我想问问，在test_spsr.json和train_spsr.json中“path”中的root应该怎么填写呢？

**Comment by Maclory** [comment]
您好，迟复为歉。root一般可以设置为code、metrics等文件夹的上一级目录，也就是整个代码项目的根目录。

**Comment by floodgone** [comment]
问题已经解决，感谢回复



在 2020-12-30 17:03:26，"Cheng Ma" <notifications@github.com> 写道：

您好，迟复为歉。root一般可以设置为code、metrics等文件夹的上一级目录，也就是整个代码项目的根目录。

**Comment by Maclory** [comment]
不客气:-)
