### ISSUE TITLE
您好，我在运行您的代码的时候遇到一个问题，期待您的答复，谢谢。在运行时，可以正常训练，但是验证时，会爆显存RuntimeError:CUDA out of memory。请问是什么原因呢

### ISSUE THREAD

**Issue by Vir-Mr-G** [Maclory/SPSR#35]

**Comment by Vir-Mr-G** [comment]
@Maclory @LiquidAmmonia

**Comment by Maclory** [comment]
你好，可能是因为验证的时候输入的图片大小过大，导致显存不够

**Comment by Vir-Mr-G** [comment]
您好：
&nbsp; &nbsp; &nbsp;很冒昧的给您发这封邮件。在运行您的SPSR代码中的评估工具箱时遇到一个问题。希望您可以帮忙解答一下。谢谢。
&nbsp; &nbsp; &nbsp;matlab.engine.MatlabExecutionError: 未定义与 'char' 类型的输入参数相对应的函数 'evaluate_results'。
&nbsp; &nbsp; &nbsp;在调用matlab时，这个函数，是您自己定义的一个函数包吗，我搜了一下，找不到，可能是我找的方向不对。
&nbsp; &nbsp; &nbsp;再次感谢，烦恼您了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Maclory/SPSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Maclory/SPSR] 您好，我在运行您的代码的时候遇到一个问题，期待您的答复，谢谢。在运行时，可以正常训练，但是验证时，会爆显存RuntimeError:CUDA out of memory。请问是什么原因呢 (#35)





 
你好，可能是因为验证的时候输入的图片大小过大，导致显存不够

**Comment by Maclory** [comment]
你好，你指的是不是这个[evaluate_results](https://github.com/Maclory/SPSR/blob/d3f6747a1dbc3b1167aacc445de217406d6bbdec/metrics/MetricEvaluation/evaluate_results.m)函数呀

**Comment by Vir-Mr-G** [comment]
您好：
&nbsp; &nbsp; &nbsp;不好意思，是我对代码的研究还不够。但既然有这个文件，为什么运行的时候会显示未定义这个函数呢。&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;您方便加个QQ联系方式吗。我的QQ是934114768.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Maclory/SPSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Maclory/SPSR] 您好，我在运行您的代码的时候遇到一个问题，期待您的答复，谢谢。在运行时，可以正常训练，但是验证时，会爆显存RuntimeError:CUDA out of memory。请问是什么原因呢 (#35)





 
你好，你指的是不是这个evaluate_results函数呀
