### ISSUE TITLE
Test with multiple GPUs

### ISSUE THREAD

**Issue by InstantWindy** [Maclory/SPSR#36]
Hi.When the test uses multiple GPUs, only one GPU is used. How to solve it? Thanks.

**Comment by Maclory** [comment]
Hi. If only one image is processed in testing, only one GPU is used. If the testing batch size is enlarged, multiple GPUs can be utilized simultaneously.

**Comment by InstantWindy** [comment]
The testing batch size is only 1, but my test picture is too big, only using a gpu will cause memory overflow. So I must set two GPUs.

**Comment by Maclory** [comment]
I would like to suggest using CPUs for recovering large testing images.
