### ISSUE TITLE
question about test

### ISSUE THREAD

**Issue by xcc19970423** [Maclory/SPSR#41]
您好，我想问一下，在测试的时候，你的代码里面pretrained_model_G填的是spsr.pth,我在训练完自己的数据集后，这个应该填哪个？并且训练完之后没有保存spsr.pth这个文件

**Comment by Maclory** [comment]
填入自己训练得到的模型路径即可

**Comment by xcc19970423** [comment]
我训练完之后没有spsr.pth这个权值文件，只有好多个关于模型G和D的权值文件，我不知道填哪个

**Comment by Maclory** [comment]
可以从G的文件中选择一个
