### ISSUE TITLE
关于使用工具箱测试自己的模型

### ISSUE THREAD

**Issue by chenjiachengzzz** [Maclory/SPSR#43]
您好，非常感谢您开源计算指标的工具箱，我有两个问题想请教您：
1）如果我想用您的工具箱，测试我自己的模型，是否需把model.mat换成自己的，还有就是怎么产生model.mat
2）SR和GT都有了，算指标的时候不是应该和模型无关了嘛，为啥要下载这个model.mat，这个model.mat的作用是？
期待收到您的回复，再次感谢作者开源这么棒的工具箱！

**Comment by Maclory** [comment]
你好，model.mat是测试时计算度量指标所需要的参数，跟超分图片无关，所以不需要替换成自己的~
