### ISSUE TITLE
I've trained model on my own dataset,I meet some questions.

### ISSUE THREAD

**Issue by 972461099** [Maclory/SPSR#6]
你好，我用你的模型在div2k上进行2倍的训练，效果很好，我想让模型的泛化能力更强，因此增加了我自己的数据集，结果出现红绿相间的像素点，（在黑白照上表现出现的是白块），请问你知道这是怎么回事吗？该如何解决？
![mmexport1587630209069](https://user-images.githubusercontent.com/23586956/80077249-d0e17a00-857f-11ea-847f-a32a3b308d34.jpg)

**Comment by Maclory** [comment]
你好，请问增加数据集是训练集吗？以及红绿像素点的情况是出现在训练过程还是测试过程呢？

**Comment by 972461099** [comment]
> 你好，请问增加数据集是训练集吗？以及红绿像素点的情况是出现在训练过程还是测试过程呢？
是的，对训练集增加数据，这种情况出现在测试的过程。

请问是否是我的数据集有问题？我增加的是高清影视数据，是两者在不同的域吗？同时我对LR数据不仅做了bicubic下采样还做了jpeg压缩处理，因为这样对减少压缩伪影有挺大的帮助（在div2k训练后效果不错）。

**Comment by Maclory** [comment]
> > 你好，请问增加数据集是训练集吗？以及红绿像素点的情况是出现在训练过程还是测试过程呢？
> > 是的，对训练集增加数据，这种情况出现在测试的过程。
> 
> 请问是否是我的数据集有问题？我增加的是高清影视数据，是两者在不同的域吗？同时我对LR数据不仅做了bicubic下采样还做了jpeg压缩处理，因为这样对减少压缩伪影有挺大的帮助（在div2k训练后效果不错）。

是的，我认为超分的性能和训练时使用的数据模态有较大关系，出现的噪点可能是新的数据带来了一定的噪声。

**Comment by 972461099** [comment]
好的，非常感谢

**Comment by Maclory** [comment]
> 好的，非常感谢

不客气
