### ISSUE TITLE
RuntimeError: unexpected EOF, expected 37475777 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by fourteen14fourteen** [Maclory/SPSR#9]
An unexpected break in the middle of the training indicates an error loading the model vgg19.
"20-05-12 14:36:42.857 - INFO: Loading pretrained model for G [/home/usst/hs/spsr/SPSR-master/experiments/pretrasin_models/RRDB_PSNR_x4.pth] ...
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main()
  File "train.py", line 84, in main
    model = create_model(opt)
  File "/home/usst/hs/spsr/SPSR-master/code/models/__init__.py", line 12, in create_model
    m = M(opt)
  File "/home/usst/hs/spsr/SPSR-master/code/models/SPSR_model.py", line 131, in __init__
    self.netF = networks.define_F(opt, use_bn=False).to(self.device)
  File "/home/usst/hs/spsr/SPSR-master/code/models/networks.py", line 170, in define_F
    use_input_norm=True, device=device)
  File "/home/usst/hs/spsr/SPSR-master/code/models/modules/architecture.py", line 551, in __init__
    model = torchvision.models.vgg19(pretrained=True)
  File "/home/usst/anaconda3/envs/torch_hs/lib/python3.6/site-packages/torchvision/models/vgg.py", line 172, in vgg19
    return _vgg('vgg19', 'E', False, pretrained, progress, **kwargs)
  File "/home/usst/anaconda3/envs/torch_hs/lib/python3.6/site-packages/torchvision/models/vgg.py", line 93, in _vgg
    progress=progress)
  File "/home/usst/anaconda3/envs/torch_hs/lib/python3.6/site-packages/torch/hub.py", line 509, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/usst/anaconda3/envs/torch_hs/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/usst/anaconda3/envs/torch_hs/lib/python3.6/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 37475777 more bytes. The file might be corrupted."

**Comment by Maclory** [comment]
Hi, this issue might be caused by lacking space or a network error. [Link1](https://github.com/huggingface/transformers/issues/1491) and [Link2](https://discuss.pytorch.org/t/loading-pretrained-model-error/10315) may be helpful to you.

**Comment by fourteen14fourteen** [comment]
Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs?

**Comment by Maclory** [comment]
> Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs?

We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs.

**Comment by fourteen14fourteen** [comment]
OK，thank you for your advise ！




| |
fourteen
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/12/2020 23:38, Cheng Ma wrote:

Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs?

We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs.

**Comment by fourteen14fourteen** [comment]
How long does it take to train on one gpu?



| |
fourteen
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/12/2020 23:40, fourteen14fourteen wrote:
OK，thank you for your advise ！




| |
fourteen
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/12/2020 23:38, Cheng Ma wrote:

Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs?

We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs.

**Comment by Maclory** [comment]
> How long does it take to train on one gpu? | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:40, fourteen14fourteen wrote: OK，thank you for your advise ！ | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:38, Cheng Ma wrote: Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs? We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

The training for our model takes several days. In fact, you can stop the training once you get a satisfactory model.

**Comment by fourteen14fourteen** [comment]
Thanks




| |
fourteen
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/12/2020 23:47, Cheng Ma wrote:

How long does it take to train on one gpu? | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:40, fourteen14fourteen wrote: OK，thank you for your advise ！ | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:38, Cheng Ma wrote: Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs? We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

The training for our model takes several days. In fact, you can stop the training once you get a satisfactory model.

**Comment by Maclory** [comment]
> Thanks | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:47, Cheng Ma wrote: How long does it take to train on one gpu? | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:40, fourteen14fourteen wrote: OK，thank you for your advise ！ | | fourteen | | 邮箱：fourteen_h@126.com | Signature is customized by Netease Mail Master On 05/12/2020 23:38, Cheng Ma wrote: Thank you for your comments. I have found the error when loading the VGG network. Just delete the downloaded network and download it again. By the way, the batch in the code is 30. Did you train with two GPUs? We trained the model with one GPU and a batchsize of 15. You can change the batchsize according to the number and memory of your GPUs. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. The training for our model takes several days. In fact, you can stop the training once you get a satisfactory model. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You are welcome.
